<#
.SYNOPSIS
Imports a cert from WASC renewal into FileMaker server.

.DESCRIPTION
Note that this script is intended to be run via the install script plugin from WASC via the batch script wrapper. As such, we use positional parameters to avoid issues with using a dash in the cmd line.

THIS SCRIPT IS INCOMPLETE AND *mostly* UNTESTED (some modifications have come in from people using it successfully)
Documentation referenced from https://technet.microsoft.com/en-us/library/aa997231(v=exchg.160).aspx

Proper information should be available here
https://github.com/PKISharp/win-acme/wiki/Install-Script
or more generally, here 
https://github.com/PKISharp/win-acme/wiki/Example-Scripts


.PARAMETER ServerHostName
ServerHostName name to use when importing the .pem files.

.PARAMETER CertificatePath
Path to the WACS certificate directory. The certificate that is imported will be "$(ServerHostName)-chain.pem" from this directory. 

.PARAMETER DebugOn
Include this switch parameter to write debug outputs for troubleshooting

#>

param(
	[Parameter(Position=0,Mandatory=$true)]
	[string]
	$ServerHostName,
    
    [Parameter(Position=1,Mandatory=$false)]
	[string]
	$CertificatePath,

	[switch]$DebugOn
)

if($DebugOn){
	$DebugPreference = "Continue"
}

<#
FileMaker Server's CStore folder is default location for Windows encrypted filemaker credentials file generated by SaveCredentials.ps1. Change the following if necessary.
#>
$FMSCStorePath = "C:\Program Files\FileMaker\FileMaker Server\CStore"
$CredsFilename = "WacsFMSCreds.xml"

# Default to FileMaker Server CStore path if no certificate path is provided
$CertificatePath = if (!$CertificatePath) {$FMSCStorePath}
Write-Host $CertificatePath
$CredsPath = Join-Path -Path $FMSCStorePath -ChildPath $CredsFilename
$CertificateFileName = "$ServerHostName-chain.pem"
$KeyfileName = "$ServerHostName-key.pem"

$ImportCertPath = Join-Path -Path $CertificatePath -ChildPath $CertificateFileName
$ImportKeyfilePath = Join-Path -Path $CertificatePath -ChildPath $Keyfilename

#load input credentials
$IC = Import-CliXml $CredsPath
$Username = $IC.Username
$Password = $IC.GetNetworkCredential().Password
Write-Host "Plaintext Password:" $PlainTextPassword

# Print debugging info to make sure the parameters arrived
if ($DebugOn) {
	Write-Host "FileMaker Server Host Name: $ServerHostName"
	Write-Host "Certificate Path: $ImportCertPath"
	Write-Host "Keyfile Path: "$ImportKeyfilePath
	Write-Host "username: "$Username
	Write-Host "password: "$Password
}

$ImportCertCmd = "fmsadmin -y -u `"$Username`" -p `"$Password`" CERTIFICATE IMPORT `"$ImportCertPath`" --keyfile `"$ImportKeyfilePath`""
$RestartServerCmd = "fmsadmin -y -u `"$Username`" -p `"$Password`" restart server"

if ($DebugOn)
    {
    Write-Host $ImportCertCmd
    Write-Host $RestartServerCmd
	}
else {
	Invoke-Expression $ImportCertCmd
	Invoke-Expression $RestartServerCmd
	}

