<#
.SYNOPSIS
Imports a cert from WASC renewal into FileMaker server.

.DESCRIPTION
Note that this script is intended to be run via the install script plugin from WASC via the batch script wrapper. As such, we use positional parameters to avoid issues with using a dash in the cmd line.

THIS SCRIPT IS INCOMPLETE AND *mostly* UNTESTED (some modifications have come in from people using it successfully)
Documentation referenced from https://technet.microsoft.com/en-us/library/aa997231(v=exchg.160).aspx

Proper information should be available here
https://github.com/PKISharp/win-acme/wiki/Install-Script
or more generally, here 
https://github.com/PKISharp/win-acme/wiki/Example-Scripts

.PARAMETER Hostname
Hostname to use when importing the .pem files.

.PARAMETER CertPath
Path to the WACS certificate directory. The certificate that is imported will be "$(host)-chain.pem" from this directory. 

.PARAMETER DebugOn
Include this switch parameter to write debug outputs for troubleshooting

.PARAMETER Usage
`InstallSSL.ps1 --host text.example.com -C C:\programdata\win-acme`
#>

param(
	[Parameter(Position=0,Mandatory=$true)]
	[string]
	$Hostname,
    
     [Parameter(Position=1,Mandatory=$false)]
	[string]
	$CertPath,

     [Parameter(Position=2,Mandatory=$false)]
	[string]
	$FmsCredsPath,

	[switch]$DebugOn
)

if($DebugOn){
	$DebugPreference = "Continue"
}

<#
C:\ProgramData\win-acme is default location for Windows encrypted filemaker credentials file generated by SaveCredentials.ps1. Change the following if necessary.
#>
$ErrorActionPreference = 'Stop'
$DEFAULT_PATH = "C:\ProgramData\win-acme"
$DEFAULT_CRED_filename = "WacsFMSCreds.xml"

Write-Host $Hostname $CertPath $FmsCredsPath
#CDefauls to win-acme folder if no certificate path is provided
# set this to something else if necessary

# the full default credential file path
$CredsPath = if ( !$FmsCredsPath )
				{
				 	Join-Path -Path $DEFAULT_PATH -ChildPath $DEFAULT_CRED_filename
				} else {
					$FmsCredsPath
				}

$CertificateFileName = "$Hostname-chain.pem"
$KeyfileName = "$Hostname-key.pem"

$ImportCertFilePath = Join-Path -Path $CertPath -ChildPath $CertificateFileName
$ImportKeyFilePath = Join-Path -Path $CertPath -ChildPath $Keyfilename

#load input credentials
$IC = Import-CliXml $CredsPath
$Username = $IC.Username
$Password = $IC.GetNetworkCredential().Password
Write-Host "Plaintext Password:" $PlainTextPassword

# Print debugging info to make sure the parameters arrived
if ($DebugOn) {
	Write-Host "FileMaker Server Host Name: $Hostname"
	Write-Host "Certificate Path: $ImportCertFilePath"
	Write-Host "Keyfile Path: "$ImportKeyFilePath
	Write-Host "username: "$Username
	Write-Host "password: "$Password
}

$ImportCertCmd = "fmsadmin -y -u `"$Username`" -p `"$Password`" CERTIFICATE IMPORT `"$ImportCertFilePath`" --keyfile `"$ImportKeyFilePath`""
$RestartServerCmd = "fmsadmin -y -u `"$Username`" -p `"$Password`" restart server"

if ($DebugOn)
    {
    Write-Host $ImportCertCmd
    Write-Host $RestartServerCmd
	}
else {
	Invoke-Expression $ImportCertCmd
	Invoke-Expression $RestartServerCmd
	}

